const items = [
    {
        name: 'Preparation',
        url: 'preparation',
        cards: [
            {
                id: 1,
                word: 'a destination',
                sentence: `I'm on the way to my destination.`,
                sentenceTwo: `We arrived at our destination very tired.`,
                uaWord: `пункт призначення`,
                uaSentence: `Я на шляху до свого місця призначення.`,
                uaSentenceTwo: `Ми прибули до нашого пункту призначення дуже втомленими.`,
                learningStatus: 'new',
            },
            {
                id: 2,
                word: 'a purpose / a goal',
                sentence: `A purpose of visit.`,
                sentenceTwo: `We have a goal to visit as many places as we can.`,
                uaWord: `ціль, мета, намір`,
                uaSentence: `Ціль візиту.`,
                uaSentenceTwo: `Ми маємо намір відвідати якомога більше місць.`,
                learningStatus: 'new',
            },
            {
                id: 3,
                word: 'abroad',
                sentence: `Are you going abroad?`,
                sentenceTwo: `I am abroad at the moment.`,
                uaWord: `за кордоном`,
                uaSentence: `Ви збираєтеся за кордон?`,
                uaSentenceTwo: `Зараз я за кордоном.`,
                learningStatus: 'new',
            },
            {
                id: 4,
                word: 'a deadline',
                sentence: `The deadline for applications is May 27th.`,
                sentenceTwo: `Some hotels have deadlines for booking rooms online.`,
                uaWord: `кінцевий термін, дедлайн`,
                uaSentence: `Кінцевий термін подачі заявок - 27 травня.`,
                uaSentenceTwo: `У деяких готелях є кінцевий термін бронювання номерів онлайн.`,
                learningStatus: 'new',
            },
            {
                id: 5,
                word: 'precaution',
                sentence: `They failed to take the necessary precautions to avoid infection.`,
                sentenceTwo: `Adequate precautions should be taken when handling it.`,
                uaWord: `запобіжний захід, обачність`,
                uaSentence: `Вони не вжили необхідних заходів для запобігання інфекції.`,
                uaSentenceTwo: `При поводженні з ними слід дотримуватися відповідних запобіжних заходів.`,
                learningStatus: 'new',
            },
            {
                id: 6,
                word: 'preparation',
                sentence: `Preparation for the trip can take a long time.`,
                sentenceTwo: `In either case, careful preparation is required.`,
                uaWord: `підготовка`,
                uaSentence: `Підготовка до подорожі може зайняти багато часу.`,
                uaSentenceTwo: `У будь-якому випадку потрібна ретельна підготовка.`,
                learningStatus: 'new',
            },
            {
                id: 7,
                word: 'to accompany / a company',
                sentence: `Children must be accompanied by adults.`,
                sentenceTwo: `If you wish, you can accompany the pictures with explanatory texts.`,
                uaWord: `супроводжувати / товариство`,
                uaSentence: `Дітей повинні супроводжувати дорослі.`,
                uaSentenceTwo: `За бажанням ви можете супроводжувати малюнки пояснювальними текстами.`,
                learningStatus: 'new',
            },
            {
                id: 8,
                word: 'to book',
                sentence: `I would like to boo a ticket.`,
                sentenceTwo: `We wanted to book a hotel room in July but there were no vacancies.`,
                uaWord: `бронювати`,
                uaSentence: `Я хотів би забронювати квиток.`,
                uaSentenceTwo: `Ми хотіли забронювати номер у готелі в липні, але вільних місць не було.`,
                learningStatus: 'new',
            },
            {
                id: 9,
                word: 'to charge',
                sentence: `Where can i charge my phone?`,
                sentenceTwo: `A quick charge to 80 percent of the batteries' capacity is possible in just 15 minutes.`,
                uaWord: `заряджати`,
                uaSentence: `Де я можу зарядити свій телефон?`,
                uaSentenceTwo: `Швидка зарядка до 80 відсотків ємності батарей можлива всього за 15 хвилин.`,
                learningStatus: 'new',
            },
            {
                id: 10,
                word: 'to (a) register / registration',
                sentence: `The registration was announced.`,
                sentenceTwo: `Firstly, a mandatory register has been brought into use.`,
                uaWord: `зареєструватися / реєстр / реєстрація`,
                uaSentence: `Оголосили реєстрацію`,
                uaSentenceTwo: `По-перше, запроваджено обов'язковий реєстр.`,
                learningStatus: 'new',
            },
        ],
    },
    {
        name: 'Packing',
        url: 'packing',
        cards: [
            {
                id: 11,
                word: 'a bottle',
                sentence: `It is forbidden to bring bottles of liquid on the plane board.`,
                sentenceTwo: `So enjoy this bottle on us.`,
                uaWord: `пляшка`,
                uaSentence: `На борт літака заборонено проносити пляшки з рідиною.`,
                uaSentenceTwo: `Тож насолоджуйтеся цією пляшкою за наш рахунок.`,
                learningStatus: 'new',
            },
            {
                id: 12,
                word: 'a can (AmE) / a tin (BrE)',
                sentence: `Actually, I have a tin of beer.`,
                sentenceTwo: `And when he lit the match, the can exploded.`,
                uaWord: `банка(жестяна), бляшанка`,
                uaSentence: `Взагалі-то, у мене є банка пива.`,
                uaSentenceTwo: `І коли він запалив сірника, бляшанка вибухнула.`,
                learningStatus: 'new',
            },
            {
                id: 13,
                word: 'a card',
                sentence: `DRC = Driver card; CTC = Controller card and COC = Company card.`,
                sentenceTwo: `Kiosks accept both cash and card.`,
                uaWord: `картка, листівка`,
                uaSentence: `КВ - картка водія; КК - картка контролера та КК - картка компанії.`,
                uaSentenceTwo: `Кіоски приймають як готівку, так і картки.`,
                learningStatus: 'new',
            },
            {
                id: 14,
                word: 'a carton',
                sentence: `A carton of orange juice.`,
                sentenceTwo: `That reminds me of a time I bought a carton of milk.`,
                uaWord: `картонна коробка (для напоїв та їжі)`,
                uaSentence: `Пакет апельсинового соку.`,
                uaSentenceTwo: `Це нагадує мені випадок, коли я купив пакет молока.`,
                learningStatus: 'new',
            },
            {
                id: 15,
                word: 'a hat / a straw hat',
                sentence: `Regardless of the season, a hat is a must-have accessory for the trip.`,
                sentenceTwo: `A straw hat is best in this heat.`,
                uaWord: `капелюх / солом'яний капелюх`,
                uaSentence: `Незалежно від пори року, капелюх є обов'язковим аксесуаром для поїздки.`,
                uaSentenceTwo: `Солом'яний капелюх - найкращий у таку спеку.`,
                learningStatus: 'new',
            },
            {
                id: 16,
                word: 'a headgear',
                sentence: `In the game protective headgear is required.`,
                sentenceTwo: `Heat and sunstroke - this trouble often happens with people who neglect headgear.`,
                uaWord: `головний убір`,
                uaSentence: `У цій грі захисний головний убір є необхідним.`,
                uaSentenceTwo: `Спека і сонячний удар - ця неприємність часто трапляється з людьми, які нехтують головними уборами.`,
                learningStatus: 'new',
            },
            {
                id: 17,
                word: 'a napkin / a wet wipe',
                sentence: `Don't forget to take wet wipes to wash sticky hands and faces.`,
                sentenceTwo: `To prepare a compress from vodka or the diluted alcohol, it is necessary to prepare the gauze napkin put four times.`,
                uaWord: `серветка / волога серветка`,
                uaSentence: `Не забудьте взяти вологі серветки для миття липких рук і облич.`,
                uaSentenceTwo: `Для приготування компресу з горілки або розведеного спирту необхідно приготувати марлеву серветку, складену вчетверо.`,
                learningStatus: 'new',
            },
            {
                id: 18,
                word: 'a purse / a wallet',
                sentence: `I've lost my wallet.`,
                sentenceTwo: `The most expensive thing I owned was my purse.`,
                uaWord: `гаманець (жіночий) / гаманець (чоловічий)`,
                uaSentence: `Я загубив гаманець.`,
                uaSentenceTwo: `Найдорожчою річчю, яка у мене була, був гаманець.`,
                learningStatus: 'new',
            },
            {
                id: 19,
                word: 'a scarf / a bandana',
                sentence: `A scarf is the perfect accessory for stylish summer evenings.`,
                sentenceTwo: ``,
                uaWord: `шарф / хустка, бандана`,
                uaSentence: `Шарф - це ідеальний аксесуар для стильних літніх вечорів.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 20,
                word: 'a set',
                sentence: `I bought a set of knives as a souvenir.`,
                sentenceTwo: `Not sold individually, only as a set.`,
                uaWord: `набір`,
                uaSentence: `Я купив сувенірний набір ножів.`,
                uaSentenceTwo: `Окремо не продається, тільки в наборі.`,
                learningStatus: 'new',
            },
            {
                id: 21,
                word: 'a suitcase',
                sentence: `You can store your suitcases here.`,
                sentenceTwo: `I have to pack my suitcase.`,
                uaWord: `валіза`,
                uaSentence: `Тут ви можете зберігати свої валізи.`,
                uaSentenceTwo: `Я маю спакувати валізу.`,
                learningStatus: 'new',
            },
            {
                id: 22,
                word: 'a towel / a bath towel',
                sentence: `There's only one bath towel in our bathroom.`,
                sentenceTwo: `Maybe I should just throw in the towel.`,
                uaWord: `рушник / банний рушник`,
                uaSentence: `У нашій ванній кімнаті є тільки один банний рушник.`,
                uaSentenceTwo: `Можливо, мені варто просто здатися.`,
                learningStatus: 'new',
            },
            {
                id: 23,
                word: 'an opener',
                sentence: `A tin opener.`,
                sentenceTwo: `A bottle opener.`,
                uaWord: `відкривачка`,
                uaSentence: `Консервний ніж.`,
                uaSentenceTwo: `Штопор.`,
                learningStatus: 'new',
            },
            {
                id: 24,
                word: 'an umbrella',
                sentence: `A beach umbrella.`,
                sentenceTwo: `I left my umbrella on the bus.`,
                uaWord: `парасоля`,
                uaSentence: `Пляжна парасоля.`,
                uaSentenceTwo: `Я залишив свою парасолю в автобусі.`,
                learningStatus: 'new',
            },
            {
                id: 25,
                word: 'flip-flops / sandals',
                sentence: `Sure, flip-flops are great for the beach.`,
                sentenceTwo: `He wears sandals, often barefoot.`,
                uaWord: `шльопанці (в'єтнамки) / сандалі`,
                uaSentence: `Звичайно, шльопанці чудово підходять для пляжу.`,
                uaSentenceTwo: `Він носить сандалі, часто ходить босоніж.`,
                learningStatus: 'new',
            },
            {
                id: 26,
                word: 'a magazine / a newspaper',
                sentence: `I bought some magazines for the trip.`,
                sentenceTwo: ``,
                uaWord: `журнал / газета`,
                uaSentence: `Я купив кілька журналів для поїздки.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 27,
                word: 'a mirror',
                sentence: `Is there a mirror in the room?`,
                sentenceTwo: ``,
                uaWord: `дзеркало`,
                uaSentence: `Чи є в номері дзеркало?`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 28,
                word: 'pants / shorts / a skirt',
                sentence: `Sponge Bob Square Pants.`,
                sentenceTwo: ``,
                uaWord: `штани / шорти / спідниця`,
                uaSentence: `Губка Боб Квадратні Штани.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 29,
                word: 'a raincoat',
                sentence: `A raincoat is an essetial item for any trip to England.`,
                sentenceTwo: ``,
                uaWord: `дощовик`,
                uaSentence: `Дощовик - найважливіший елемент для будь-якої поїздки в Англію.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 30,
                word: 'a shirt / a T-shirt / a blouse',
                sentence: ``,
                sentenceTwo: ``,
                uaWord: `сорочка / футболка / блузка`,
                uaSentence: ``,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 31,
                word: 'slippers',
                sentence: `He put on his bathrobe and slippers.`,
                sentenceTwo: ``,
                uaWord: `тапочки`,
                uaSentence: `Він надів халат і тапочки.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 32,
                word: 'sunglasses / a sunscreen',
                sentence: `Wear sunglasses to protect vulnerable skin around the eyes.`,
                sentenceTwo: ``,
                uaWord: `сонцезахисні окуляри / сонцезахисний крем`,
                uaSentence: `Одягайте окуляри для захисту вразливої шкіри навколо очей.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 33,
                word: 'thermal underwear',
                sentence: `Thermal underwear is an absolute must for a ski holiday.`,
                sentenceTwo: ``,
                uaWord: `термобілизна`,
                uaSentence: `Термобілизна - необхідна річ для лижного відпочинку.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 34,
                word: 'to pack / to unpack',
                sentence: `Why are you packing?`,
                sentenceTwo: ``,
                uaWord: `пакувати(ся) / розпаковувати(ся)`,
                uaSentence: `Чому ви пакуєте речі?`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 35,
                word: 'a toiletry bag',
                sentence: `Personal hygiene items.`,
                sentenceTwo: `I always carry a toiletry bag with me.`,
                uaWord: `косметичка`,
                uaSentence: `Предмети особистої гігієни.`,
                uaSentenceTwo: `Я завжди ношу із собою косметичку.`,
                learningStatus: 'new',
            },
            {
                id: 36,
                word: 'trunks / a swimsuit',
                sentence: `Take your trunks with you!`,
                sentenceTwo: ``,
                uaWord: `плавки / купальник`,
                uaSentence: `Візьми із собою плавки!`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 37,
                word: 'upside down',
                sentence: `I've turned the house upside down looking for that air ticket.`,
                sentenceTwo: ``,
                uaWord: `догори ногами`,
                uaSentence: `Я перевернув будинок догори ногами, шукаючи цей авіаквиток.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
        ],
    },
    {
        name: 'Airport',
        url: 'airport',
        cards: [
            {
                id: 38,
                word: 'a cabin',
                sentence: `A first-class cabin.`,
                sentenceTwo: `A second-class cabin.`,
                uaWord: `кібіна / каюта / салон літака`,
                uaSentence: `Каюта першого класу.`,
                uaSentenceTwo: `Каюта другого класу.`,
                learningStatus: 'new',
            },
            {
                id: 39,
                word: 'a departure lounge',
                sentence: `I've waited for the flight in the departure lounge for 3 hours.`,
                sentenceTwo: ``,
                uaWord: `зал очікування`,
                uaSentence: `Я чекав на рейс 3 години в залі очікування.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 40,
                word: 'a direct flight / a connected flight',
                sentence: `I've booked you a direct flight to Paris.`,
                sentenceTwo: ``,
                uaWord: `прямий рейс / пересадковий рейс`,
                uaSentence: `Я забронював вам прямий рейс до Парижа.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 41,
                word: 'a foreigner / foreign',
                sentence: `When traveling, you get to know a foreign culture.`,
                sentenceTwo: `The country may have a cautious attitude towards foreigners.`,
                uaWord: `іноземець / іноземний, закордонний`,
                uaSentence: `Подорожуючи, ти пізнаєш іноземну культуру.`,
                uaSentenceTwo: `У цій країні може бути насторожене ставлення до іноземців.`,
                learningStatus: 'new',
            },
            {
                id: 42,
                word: 'a gate',
                sentence: `Your flight is now boarding at gate six.`,
                sentenceTwo: ``,
                uaWord: `ворота(повітряні)`,
                uaSentence: `Посадка на ваш літак проводиться біля повітряних воріт номер шість.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 43,
                word: 'arrival time / departure time',
                sentence: `Where can i find the arrival time of my flight?`,
                sentenceTwo: ``,
                uaWord: `час прибуття / час вильоту`,
                uaSentence: `Де я можу дізнатись час прибуття мого літака?`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 44,
                word: 'baggage (AmE) / luggage (BrE)',
                sentence: `Weigh your baggage/luggage.`,
                sentenceTwo: ``,
                uaWord: `багаж`,
                uaSentence: `Зважте свій багаж.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 45,
                word: 'baggage reclaim / lost luggage',
                sentence: `Lost luggage will be returned to you in 3 days.`,
                sentenceTwo: ``,
                uaWord: `місце отримання багажу / втрачений багаж`,
                uaSentence: `Загублений багаж вам повернуть через 3 дні.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 46,
                word: 'a boarding pass / a landing card',
                sentence: `May I see your boarding pass?`,
                sentenceTwo: ``,
                uaWord: `посадковий талон / посадкова картка (з особистими даними)`,
                uaSentence: `Могли б ви показати посадковий талон?`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 47,
                word: 'customs / a custom officer',
                sentence: `We passed customs control.`,
                sentenceTwo: ``,
                uaWord: `митниця, митний збір / митник`,
                uaSentence: `Ми пройшли митний контроль.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 48,
                word: 'delayed / canceled',
                sentence: `You can get a compensation for a delayed or canceled flight.`,
                sentenceTwo: ``,
                uaWord: `затриманий (рейс) / скасований (рейс)`,
                uaSentence: `Ви можете отримати компенсацію за затриманий або скасований рейс.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 49,
                word: 'excess baggage / baggage allowance',
                sentence: `He arrived with 40 kilos of excess baggage.`,
                sentenceTwo: ``,
                uaWord: `надлишковий багаж / норма перевезення багажу`,
                uaSentence: `Він прибув із 40 кілограмами надлишкового багажу.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
            {
                id: 50,
                word: 'a flight attendant / cabine crew',
                sentence: `He is a flight attendant from Italy.`,
                sentenceTwo: ``,
                uaWord: `стюард, стюардеса / екіпаж літака`,
                uaSentence: `Він стюард із Італії.`,
                uaSentenceTwo: ``,
                learningStatus: 'new',
            },
        ],
    },

]

export { items }

// tempalte

let a = [
    {
        name: 'Preparation',
        url: 'preparation',
        cards: [
            {
                id: 1,
                word: 'a destination',
                sentence: `I'm on the way to my destination.`,
                sentenceTwo: `We arrived at our destination very tired.`,
                uaWord: `пункт призначення`,
                uaSentence: `Я на шляху до свого місця призначення.`,
                uaSentenceTwo: `Ми прибули до нашого пункту призначення дуже втомленими.`,
                learningStatus: 'new',
            },
        ],
    },
]



// lessonName: 'Rental car',
// url: 'travel/2',
// cards: [
//     {
//         word: 'to hire / to rent',
//         uaWord: 'винаймати, брати на прокат, орендувати',
//         sentence: 'This phrase will help you hire a car.',
//         uaSentence: `Ця фраза допоможе вам орендувати автомобіль.`,
//         learningStatus: 'new',
//     },
// ],